### PR TITLE
Import a cat written in C#.

### PR DESCRIPTION
**Pull request by sbennett1990**

### CODE REVIEW

**Comment by ibara** [comment]
Could you squash this then into a single commit? Otherwise, looks good.

**Comment by sbennett1990** [comment]
Apologies, I'm not very familiar with git. I added the last 3 commits after the initial pull request and didn't know they would all get tacked on. If I knew how to compress it into 1 commit I would!

**Comment by ibara** [comment]
I'm not much of a git aficionado either. But I think it's:
git reset origin/master
git add --all
git commit

I don't want to do it for you because I think it screws up the authoring if I do.

**Comment by sbennett1990** [comment]
Easier (to me) way: I deleted my fork. I will re-fork and do 1 commit, then reissue a pull request. So you can ignore/dispose of this pull request.

**Comment by ibara** [comment]
Sounds good. I'll close this one and import the other one.

**Pull request closed without merging**
